'''
    Exception : which disturb the normal flow of program
                to handle this kind of exception it's call exception handling

                exception handling is possible with try and except block

                
'''

try:
    print(a)
except:
    print("somthing went wrong") 